#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config left_padding 50
bspc config border_width 3
bspc config window_gap 10

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#B4BEFE"
bspc config normal_border_color "#6C7086"

export BSPWM_ROOT="$HOME/.config/bspwm"
export EWW_ROOT="$BSPWM_ROOT/eww"
export SCRIPT_ROOT="$BSPWM_ROOT/scripts"
export ROFI_ROOT="$BSPWM_ROOT/rofi"

. "$BSPWM_ROOT/rules"
. "$BSPWM_ROOT/profile"
