#!/bin/sh

case "$1" in
"mute")
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    ;;
"up")
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SOURCE@ 5%+
    ;;
"down")
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SOURCE@ 5%-
    ;;
*)
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SOURCE@ "${1}%"
    ;;
esac
