#!/bin/sh

case "$1" in
"mute")
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    ;;
"up")
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 10%+
    ;;
"down")
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 10%-
    ;;
*)
    wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ "$1%"
    ;;
esac
